export * from './serviceFaqTypes'
export * from './serviceHeroTypes'
export * from './serviceWhyTypes'
export * from './serviceTableTypes'
export * from './serviceListTypes'
export * from './serviceContactUsTypes'